# Generated by Django 3.0.11 on 2021-04-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_article_to_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['dtCreate']},
        ),
    ]
