# Generated by Django 3.0.11 on 2021-03-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0070_auto_20210329_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='accept_tutor',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='tutor',
        ),
    ]
