# Generated by Django 3.0.11 on 2021-03-29 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0071_auto_20210329_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrauser',
            name='acceptSponsor',
        ),
        migrations.RemoveField(
            model_name='extrauser',
            name='sponsorOf',
        ),
        migrations.AddField(
            model_name='profil',
            name='acceptSponsor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='sponsorOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alumni.Profil'),
        ),
    ]
