# Generated by Django 3.0.11 on 2021-03-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0072_auto_20210329_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='sponsorOf',
            new_name='sponsorBy',
        ),
    ]
