# Generated by Django 3.0.11 on 2021-03-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0073_auto_20210329_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='sponsorBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.Profil'),
        ),
    ]
